import { Course, CourseCategory, InstructorProfile, User, Review } from '@/types';

export const mockCategories: CourseCategory[] = [
  { id: '1', name: 'Programming', nameAm: 'ፕሮግራሚንግ', slug: 'programming', icon: '💻', orderIndex: 1, isActive: true },
  { id: '2', name: 'Business', nameAm: 'ንግድ', slug: 'business', icon: '📊', orderIndex: 2, isActive: true },
  { id: '3', name: 'Design', nameAm: 'ዲዛይን', slug: 'design', icon: '🎨', orderIndex: 3, isActive: true },
  { id: '4', name: 'Marketing', nameAm: 'ማርኬቲንግ', slug: 'marketing', icon: '📈', orderIndex: 4, isActive: true },
  { id: '5', name: 'Languages', nameAm: 'ቋንቋዎች', slug: 'languages', icon: '🌍', orderIndex: 5, isActive: true },
  { id: '6', name: 'Personal Development', nameAm: 'የግል እድገት', slug: 'personal-development', icon: '🧠', orderIndex: 6, isActive: true },
];

export const mockInstructors: InstructorProfile[] = [
  {
    id: '1',
    userId: 'u1',
    headline: 'Full Stack Developer & Tech Educator',
    biography: '10+ years of experience in web development. Taught over 100,000 students worldwide.',
    totalStudents: 45230,
    totalCourses: 12,
    totalRevenue: 125000,
    averageRating: 4.8,
    isVerified: true,
    user: {
      id: 'u1',
      email: 'abebe@example.com',
      firstName: 'Abebe',
      lastName: 'Bekele',
      role: 'INSTRUCTOR',
      isVerified: true,
      isActive: true,
      language: 'en',
      profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
      createdAt: '2023-01-01',
      updatedAt: '2024-01-01',
    },
  },
  {
    id: '2',
    userId: 'u2',
    headline: 'Data Science & Machine Learning Expert',
    biography: 'PhD in Computer Science. Formerly at Google AI. Passionate about making AI accessible.',
    totalStudents: 32150,
    totalCourses: 8,
    totalRevenue: 98000,
    averageRating: 4.9,
    isVerified: true,
    user: {
      id: 'u2',
      email: 'tigist@example.com',
      firstName: 'Tigist',
      lastName: 'Haile',
      role: 'INSTRUCTOR',
      isVerified: true,
      isActive: true,
      language: 'am',
      profileImage: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=face',
      createdAt: '2023-02-01',
      updatedAt: '2024-01-01',
    },
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    instructorId: '1',
    instructor: mockInstructors[0],
    categoryId: '1',
    category: mockCategories[0],
    title: 'Complete Web Development Bootcamp 2024',
    titleAm: 'ሙሉ የድር ልማት ቡትካምፕ 2024',
    slug: 'complete-web-development-bootcamp-2024',
    description: 'Become a full-stack web developer with just ONE course. HTML, CSS, JavaScript, Node, React, MongoDB, and more!',
    descriptionAm: 'በአንድ ኮርስ ብቻ ሙሉ ስታክ ዌብ ዴቨሎፐር ይሁኑ። HTML፣ CSS፣ JavaScript፣ Node፣ React፣ MongoDB እና ተጨማሪ!',
    thumbnail: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600&h=400&fit=crop',
    price: 1499,
    discountPrice: 299,
    currency: 'ETB',
    level: 'BEGINNER',
    status: 'PUBLISHED',
    totalDuration: 3600,
    totalLessons: 156,
    enrollmentCount: 12543,
    averageRating: 4.8,
    totalReviews: 2341,
    isFeatured: true,
    isPopular: true,
    isPublished: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: '2',
    instructorId: '2',
    instructor: mockInstructors[1],
    categoryId: '1',
    category: mockCategories[0],
    title: 'Python for Data Science and Machine Learning',
    titleAm: 'ፓይዘን ለዳታ ሳይንስ እና ማሽን ለርኒንግ',
    slug: 'python-data-science-ml',
    description: 'Learn Python for data analysis, visualization, and machine learning. Perfect for beginners and intermediate programmers.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&h=400&fit=crop',
    price: 1299,
    discountPrice: 349,
    currency: 'ETB',
    level: 'INTERMEDIATE',
    status: 'PUBLISHED',
    totalDuration: 2880,
    totalLessons: 124,
    enrollmentCount: 8921,
    averageRating: 4.9,
    totalReviews: 1876,
    isFeatured: true,
    isPopular: true,
    isPublished: true,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-20',
  },
  {
    id: '3',
    instructorId: '1',
    instructor: mockInstructors[0],
    categoryId: '3',
    category: mockCategories[2],
    title: 'UI/UX Design Masterclass',
    titleAm: 'UI/UX ዲዛይን ማስተርክላስ',
    slug: 'ui-ux-design-masterclass',
    description: 'Master user interface and user experience design. Learn Figma, design principles, and create stunning interfaces.',
    thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop',
    price: 999,
    discountPrice: 249,
    currency: 'ETB',
    level: 'ALL_LEVELS',
    status: 'PUBLISHED',
    totalDuration: 1800,
    totalLessons: 78,
    enrollmentCount: 5432,
    averageRating: 4.7,
    totalReviews: 892,
    isFeatured: false,
    isPopular: true,
    isPublished: true,
    createdAt: '2024-01-10',
    updatedAt: '2024-01-25',
  },
  {
    id: '4',
    instructorId: '2',
    instructor: mockInstructors[1],
    categoryId: '2',
    category: mockCategories[1],
    title: 'Digital Marketing Complete Guide',
    titleAm: 'ዲጂታል ማርኬቲንግ ሙሉ መመሪያ',
    slug: 'digital-marketing-complete-guide',
    description: 'Learn SEO, social media marketing, email marketing, and paid advertising to grow any business online.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&h=400&fit=crop',
    price: 899,
    discountPrice: 199,
    currency: 'ETB',
    level: 'BEGINNER',
    status: 'PUBLISHED',
    totalDuration: 2400,
    totalLessons: 96,
    enrollmentCount: 7654,
    averageRating: 4.6,
    totalReviews: 1234,
    isFeatured: true,
    isPopular: false,
    isPublished: true,
    createdAt: '2024-01-12',
    updatedAt: '2024-01-28',
  },
  {
    id: '5',
    instructorId: '1',
    instructor: mockInstructors[0],
    categoryId: '5',
    category: mockCategories[4],
    title: 'Learn Amharic for Beginners',
    titleAm: 'ለጀማሪዎች አማርኛ ይማሩ',
    slug: 'learn-amharic-beginners',
    description: 'Start speaking Amharic from day one! Learn the alphabet, vocabulary, grammar, and conversational skills.',
    thumbnail: 'https://images.unsplash.com/photo-1519222970733-f546218fa6d7?w=600&h=400&fit=crop',
    price: 599,
    discountPrice: 149,
    currency: 'ETB',
    level: 'BEGINNER',
    status: 'PUBLISHED',
    totalDuration: 1200,
    totalLessons: 48,
    enrollmentCount: 3210,
    averageRating: 4.9,
    totalReviews: 567,
    isFeatured: false,
    isPopular: false,
    isPublished: true,
    createdAt: '2024-01-15',
    updatedAt: '2024-01-30',
  },
  {
    id: '6',
    instructorId: '2',
    instructor: mockInstructors[1],
    categoryId: '6',
    category: mockCategories[5],
    title: 'Leadership & Management Skills',
    titleAm: 'የአመራር እና አስተዳደር ክህሎቶች',
    slug: 'leadership-management-skills',
    description: 'Develop essential leadership skills. Learn team management, communication, decision-making, and more.',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop',
    price: 799,
    discountPrice: 179,
    currency: 'ETB',
    level: 'INTERMEDIATE',
    status: 'PUBLISHED',
    totalDuration: 1800,
    totalLessons: 64,
    enrollmentCount: 4567,
    averageRating: 4.7,
    totalReviews: 789,
    isFeatured: false,
    isPopular: true,
    isPublished: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-02-01',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    courseId: '1',
    studentId: 's1',
    student: {
      id: 's1',
      email: 'student1@example.com',
      firstName: 'Kebede',
      lastName: 'Mengistu',
      role: 'STUDENT',
      isVerified: true,
      isActive: true,
      language: 'en',
      createdAt: '2023-06-01',
      updatedAt: '2024-01-01',
    },
    rating: 5,
    title: 'Best course ever!',
    content: 'This course completely changed my career. I went from knowing nothing to getting a job as a junior developer in just 4 months!',
    visible: true,
    helpfulCount: 234,
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    courseId: '1',
    studentId: 's2',
    student: {
      id: 's2',
      email: 'student2@example.com',
      firstName: 'Meron',
      lastName: 'Tadesse',
      role: 'STUDENT',
      isVerified: true,
      isActive: true,
      language: 'am',
      createdAt: '2023-07-01',
      updatedAt: '2024-01-01',
    },
    rating: 5,
    title: 'ኮርሱን እወደዋለሁ!',
    content: 'አስተማሪው በጣም ግልጽ ነው እና ፕሮጀክቶቹ በጣም ተግባራዊ ናቸው። ለሁሉም ሰው እመክራለሁ!',
    visible: true,
    helpfulCount: 189,
    createdAt: '2024-01-22',
  },
  {
    id: '3',
    courseId: '2',
    studentId: 's3',
    student: {
      id: 's3',
      email: 'student3@example.com',
      firstName: 'Solomon',
      lastName: 'Gebre',
      role: 'STUDENT',
      isVerified: true,
      isActive: true,
      language: 'en',
      createdAt: '2023-08-01',
      updatedAt: '2024-01-01',
    },
    rating: 5,
    title: 'Excellent for Data Science beginners',
    content: 'Tigist explains complex concepts so clearly. The hands-on projects really helped me understand machine learning.',
    visible: true,
    helpfulCount: 156,
    createdAt: '2024-01-25',
  },
];

export const formatDuration = (minutes: number): string => {
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hours === 0) return `${mins}m`;
  if (mins === 0) return `${hours}h`;
  return `${hours}h ${mins}m`;
};

export const formatPrice = (price: number, currency: string = 'ETB'): string => {
  return new Intl.NumberFormat('en-ET', {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
  }).format(price);
};
